### ISSUE TITLE
Re-fetch channel manifest (time interval)

### ISSUE THREAD

**Issue by foresterre** [foresterre/cargo-msrv#1]
We currently fetch the channel manifest only once on the first run, unless the cached file is removed.
This behaviour is unwanted as we need to deal with changes (every new Rust minor version update). Thus we need to add the ability to download a new copy of the channel manifest.

One possibility is to use the `directories` crate (which is already included as dependency) and store a last checked on date in a file. Then we can take a delta time and if it is larger than some fixed duration (e.g. 1 day), we re-fetch the channel manifest and update the last checked date.

https://github.com/foresterre/cargo-msrv/blob/master/src/fetch.rs#L172

**Comment by korrat** [comment]
I'd like to take a stab at this

**Comment by foresterre** [comment]
Thanks again!
