### ISSUE TITLE
Allow users to select the rust-releases source

### ISSUE THREAD

**Issue by foresterre** [foresterre/cargo-msrv#101]
* Paves the way to support nightly, when support in rust-releases becomes available
* Alleviates bugs like #94
* No source is perfect, or long-term guaranteed to work: having more sources means there's more likely one you will like

Available sources: https://docs.rs/rust-releases/0.16.0/rust_releases/#implemented-sources

**Comment by king-11** [comment]
It is possible to specify use of only `nightly` channel while using cargo-msrv?

**Comment by foresterre** [comment]
Nightly is currently not supported by `cargo-msrv`. It is waiting for `rust-releases` to add support, which is being implemented and should be included in the next `rust-releases` version.
