### ISSUE TITLE
support x86_64-unknown-linux-musl target

### ISSUE THREAD

**Issue by robjtede** [foresterre/cargo-msrv#1018]
and publish musl binary to releases

I'm working on a PR for this but wanted to track here as well in case I don't finish it

**Comment by foresterre** [comment]
I re-opened this issue because of: https://github.com/foresterre/cargo-msrv/actions/runs/11252915778/job/31287075636

**Comment by robjtede** [comment]
Always tricky to check CI changes. Agree looks easy to fix. I could sort it out tomorrow.

**Comment by foresterre** [comment]
Thanks! that seems to have worked :smile:

**Comment by robjtede** [comment]
Nice!
