### ISSUE TITLE
cargo msrv find --set

### ISSUE THREAD

**Issue by cdown** [foresterre/cargo-msrv#1047]
One of my usual workflows during dep upgrades is to do `cargo msrv find`, then `cargo msrv set`. But this is a pain, because it requires manually copying the new version to `cargo msrv set`. My workflow would benefit from something like `cargo msrv find --set`, which would set the found MSRV.

This looks relatively straightforward to implement, but before I submit a PR I wanted to check on the ergonomics and concept. Thanks!

**Comment by foresterre** [comment]
`cargo msrv --write-msrv` does this exact thing :)

**Comment by cdown** [comment]
Oh wow, how did I miss that :-) Thank you! I'll submit a PR for an alias then.
