### ISSUE TITLE
Refactor Output

### ISSUE THREAD

**Issue by foresterre** [foresterre/cargo-msrv#182]
issue:
* trait Output doesn't scale
  * Why: Output was designed when cargo-msrv did one thing: find the MSRV
  * What changed: cargo-msrv now supports several subcommands
  * Each subcommand has their own output requirements
  * There is some overlap, but not 1-on-1
  * To accommodate for the non-overlapping parts, conditionals have to be introduced in places where you'd rather not have them
  * Alternatively, we could implement Output not just for output types (e.g. Json, Human, TestCollector) $OT$, but also separately for each subcommand (e.g. find,  list, set, verify) $S$
  * However this will require $|OT| \cdot |S|$ implementations

**Comment by danieleades** [comment]
is this referring to the modules that i've refactored in #211, #212, and #213?

**Comment by foresterre** [comment]
Hi Daniel,

Thanks for the PR's; I haven't quite had the time yet to look at them yet, I hope to do so in the near future.

This issue refers to the [Output](https://github.com/foresterre/cargo-msrv/blob/main/src/reporter/mod.rs#L18-L32), which doesn't quite scale with the amount of recently added sub commands. Instead, I wanted to experiment a bit with making output more specific to each subcommand, while still keeping a generic way to specify the type of output. I also wanted to separate the concerns of the output and the action logic of a subcommand.

**Comment by foresterre** [comment]
Experiment 3: https://github.com/foresterre/rust-experiment-air3/blob/main/src/main.rs

**Comment by foresterre** [comment]
To be implemented solution: use https://github.com/foresterre/storyteller, based on https://github.com/foresterre/rust-experiment-air3
