### ISSUE TITLE
MSRV bug

### ISSUE THREAD

**Issue by JohnScience** [foresterre/cargo-msrv#244]
```text
PS C:\Users\demen\Documents\GitHub\include_display_mode_tex> cargo check --all
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
PS C:\Users\demen\Documents\GitHub\include_display_mode_tex> cargo msrv
Fetching index
Determining the Minimum Supported Rust Version (MSRV) for toolchain x86_64-pc-windows-msvc
Using check command cargo check --all
   Done Bad check for 1.57.0      ██████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 00:00:02
   Failed check command cargo check --all didn't succeed
Unable to find a Minimum Supported Rust Version (MSRV).

If you think this result is erroneous, please run: `cargo check --all` manually.

If the above does succeed, or you think cargo-msrv errored in another way, please feel free to
report the issue at: https://github.com/foresterre/cargo-msrv/issues

Thank you in advance!
PS C:\Users\demen\Documents\GitHub\include_display_mode_tex> cargo --version
cargo 1.59.0-nightly (fcef61230 2021-12-17)
```

Source: https://github.com/JohnScience/include_display_mode_tex/commit/e859ad9a90ce94d1e253aac2dd16c85996644954

**Comment by foresterre** [comment]
Thanks for the report! :)

I've ran cargo-msrv on your repo (on the linked commit `e859ad9a90ce94d1e253aac2dd16c85996644954`), and found that you require a nightly feature, which is not yet present in the latest stable Rust toolchain ([1.57](https://blog.rust-lang.org/2021/12/02/Rust-1.57.0.html)):

```
cargo check --all
    Checking include_display_mode_tex v0.1.0 (/home/user/ws/include_display_mode_tex)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/lib.rs:1:12
  |
1 | #![feature(proc_macro_span)]
  |            ^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `include_display_mode_tex` due to previous error
```

As a result, there's no stable Rust toolchain which could be described as the minimum Rust version.

I saw you listed 1.59 as the MSRV in the [Cargo Manifest](https://github.com/JohnScience/include_display_mode_tex/blob/3dbedcdf0a5a780cb54bdef679f01673918da5fb/Cargo.toml#L6) on your main branch; looking at https://github.com/rust-lang/rust/issues/54725, this feature does not seem to be included for promotion to the upcoming 1.59 beta (13 January 2022). To the best of my knowledge, it's also unusual to use an unreleased toolchain version as MSRV.

Hope this helps! If you've questions or comments, feel free to comment :).

**Comment by JohnScience** [comment]
So what would you suggest to do? Should I omit the field entirely?

**Comment by foresterre** [comment]
> So what would you suggest to do? Should I omit the field entirely?

While relying on nightly features, I would omit the `rust-version` key. 

Aside from the question whether specifying a nightly version would be sensible or not, they can't be specified as they have no valid version number (two or three component semver number), see https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field.

NB: if you require a minimum (or specific) nightly toolchain you can use the [toolchain-file](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) to pin a specific toolchain, and check-in the toolchain file into your repository.

**Comment by JohnScience** [comment]
@foresterre Thank you so much!
