### ISSUE TITLE
Add support for virtual manifests

### ISSUE THREAD

**Issue by foresterre** [foresterre/cargo-msrv#295]
> Common setup: A workspace with crates a and b. a does not depend on b, it's not important if b depends on a. a has `rust-version = "1.56"`, b has `rust-version = "1.58"`. b does not build with 1.56.
>
> Issue 1: No workspace support. Ideally I'd just run `verify` in the workspace directory and it would iterate over the crates. That is not supported. `verify` expects a `package` section in the virtual manifest.

_Originally reported by @cschramm in #293_

Cargo reference: [Virtual manifest](https://doc.rust-lang.org/cargo/reference/workspaces.html#virtual-manifest)

**Comment by foresterre** [comment]
Current output of https://github.com/foresterre/cargo-msrv-issue-293: 
```
Fetching index
Determining the Minimum Supported Rust Version (MSRV) for toolchain x86_64-pc-windows-msvc
Using check command cargo check

Check for toolchain '1.57.0-x86_64-pc-windows-msvc' failed with:
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ error: package `b v0.1.0 (/ws/cargo-msrv-issue-293/b)` cannot be built because it requires rustc 1.58 or         │
│ newer, while the currently active rustc version is 1.57.0                                                        │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Check for toolchain '1.58.1-x86_64-pc-windows-msvc' succeeded
   Finished The MSRV is: 1.58.1   █████████████████████████████████████████████████████████████████████████████ 00:00:01

```

**Comment by max-sixty** [comment]
I think we can close, thanks to https://github.com/foresterre/cargo-msrv/pull/882
