### ISSUE TITLE
Allow skipping patch version in CLI

### ISSUE THREAD

**Issue by jaskij** [foresterre/cargo-msrv#340]
```shell
$ cargo msrv --bisect --min 1.54  
unexpected end of input while parsing minor version number
```
It would make a lot of sense to interpret that as either `1.54.0` or latest patch in `1.54`, instead of failing.

**Comment by foresterre** [comment]
Absolutely 😅! Thanks for the request :)

Duplicate of https://github.com/foresterre/cargo-msrv/issues/278

**Comment by jaskij** [comment]
Ah, sorry for the duplicate.

**Comment by foresterre** [comment]
No worries! :)
