### ISSUE TITLE
Support simple output format

### ISSUE THREAD

**Issue by spenserblack** [foresterre/cargo-msrv#370]
First, thank you for making this crate!

I made a [simple GitHub Action](https://github.com/spenserblack/actions-msrv) so that I could use this during workflows. One of the things I've noticed is that there doesn't seem to be simple output, but either a "pretty" output for humans, or multiple JSON outputs.

For the purposes of writing shell scripts to check the MSRV, I think it would be even beneficial to have an output format that does nothing but:
- Prints the version and exits 0
- Prints an error like "could not find version" to STDERR and exits 1

This would remove the need for a tool like `jq` to parse the output, and shell scripts that use `cargo msrv` could be simplified to something vaguely like
```shell
# obviously something more useful would happen than just cat to STDOUT :)
cargo msrv > version 2> error || cat error && cat version
```

**Comment by foresterre** [comment]
Sounds plausible! I'll see what I can do :)

**Comment by foresterre** [comment]
I'm currently working on implementing a new way to report output to the user. I hope to complete that process this or next week. After that process is complete, I'll add this, and then we're about ready for a new release as well.

**Comment by foresterre** [comment]
In #431 (merged), I added the minimal output mode, accessible via `cargo msrv --output-format minimal`.

Running your example script gives:

A successful run:
```
$ cargo msrv --output-format minimal > version 2> error || cat error && cat version
1.56.1
```


A failed run (i.e. no compatible version found):
```
$ cargo msrv --output-format minimal > version 2> error || cat error && cat version
none
```

Additional documentation can be found in the book [here](https://foresterre.github.io/cargo-msrv/output-formats/minimal.html).

If you find a bug, or like to have this implementation changed (e.g. have more details about what went wrong, I would be happy to implement this as well).

**Comment by spenserblack** [comment]
This is awesome, thanks!
