### ISSUE TITLE
Output of `cargo msrv`?

### ISSUE THREAD

**Issue by chipsenkbeil** [foresterre/cargo-msrv#39]
Is there supposed to be output for running `cargo msrv`? I tried it and followed along with `htop` as it worked backwards through rust versions, assuming that when it stopped at 1.44.0 that the last version supported was 1.45.0, but this gets a little confusing, especially if I'm working in multiple projects.

Is there something I missed?

**Comment by foresterre** [comment]
Hi,

Thanks for reporting this issue!
I also don't see output anymore... :cry: 

The current output was already sub-optimal so this is as good a reason as any to look at UI improvements   soon!

**Comment by foresterre** [comment]
Fixed in #43, an issue for improved user output can be found at #41.

Output for this crate should look similar to:
![image](https://user-images.githubusercontent.com/5955761/104409636-ff1c4500-5566-11eb-8886-e675a3365206.png)

**Comment by foresterre** [comment]
With #49, the UI now looks like this:

![s](https://i.imgur.com/5hAzJQu.gif)
