### ISSUE TITLE
Feature request: accept `--manifest-path`

### ISSUE THREAD

**Issue by CAD97** [foresterre/cargo-msrv#412]
Notably, this will allow cargo-msrv to run under [cargo-hack](https://lib.rs/crates/cargo-hack) for use in workspaces and to benefit from cargo-hack's detach-from-workspace implementation.

Specifically, I'd love to be able to `cargo hack --workspace minimal-versions msrv verify -- cargo check --all-features`, but this ends up running `cargo msrv verify --manifest-path subcrate\Cargo.toml -- cargo check --all-features` which cargo-msrv then rejects.

The desired behavior is fairly simple: retrieve the rust-version key from the given manifest path, and then forward the `--manifest-path` argument to the check invocation.

Running under cargo-hack also gives workspace support for free.

**Comment by foresterre** [comment]
Sounds great! I'll add it soon!

**Comment by foresterre** [comment]
I've tested #420 with `cargo-hack` on  a repo with a workspace ([*](https://github.com/foresterre/sic)), which seems to give the desired results.

Will be included in `cargo-msrv 0.16`. Thanks for the request!

<details>
<summary>Output of `cargo hack --workspace msrv verify -- cargo check --all-features` </summary>

sic on  main [$] is 📦 v0.20.0 via 🦀 v1.62.0 took 2s
❯ cargo hack --workspace msrv verify -- cargo check --all-features
info: running `cargo msrv verify -- cargo check --all-features` on sic_cli_ops (1/8)
  [Meta]  cargo-msrv 0.15.1 (8dcc466)

Compatibility Check #1: Rust 1.56.1
    [OK]  Is compatible

info: running `cargo msrv verify -- cargo check --all-features` on sic_image_engine (2/8)
  [Meta]  cargo-msrv 0.15.1 (8dcc466)

Compatibility Check #1: Rust 1.56.1
    [OK]  Is compatible

info: running `cargo msrv verify -- cargo check --all-features` on sic_core (3/8)
  [Meta]  cargo-msrv 0.15.1 (8dcc466)

Compatibility Check #1: Rust 1.56.1
    [OK]  Is compatible

info: running `cargo msrv verify -- cargo check --all-features` on sic_io (4/8)
  [Meta]  cargo-msrv 0.15.1 (8dcc466)

Compatibility Check #1: Rust 1.56.1
    [OK]  Is compatible

info: running `cargo msrv verify -- cargo check --all-features` on sic_testing (5/8)
  [Meta]  cargo-msrv 0.15.1 (8dcc466)

Compatibility Check #1: Rust 1.56.1
    [OK]  Is compatible

info: running `cargo msrv verify -- cargo check --all-features` on sic_parser (6/8)
  [Meta]  cargo-msrv 0.15.1 (8dcc466)

Compatibility Check #1: Rust 1.56.1
    [OK]  Is compatible

info: running `cargo msrv verify -- cargo check --all-features` on pack-release (7/8)
  [Meta]  cargo-msrv 0.15.1 (8dcc466)

Compatibility Check #1: Rust 1.59.0
    [OK]  Is compatible

info: running `cargo msrv verify -- cargo check --all-features` on sic (8/8)
  [Meta]  cargo-msrv 0.15.1 (8dcc466)

Compatibility Check #1: Rust 1.56.1
    [OK]  Is compatible

</details>
