### ISSUE TITLE
Add bisect search strategy

### ISSUE THREAD

**Issue by foresterre** [foresterre/cargo-msrv#45]
* requires `--minimum <version>` (default: [Rust 1.31](https://blog.rust-lang.org/2018/12/06/Rust-1.31-and-rust-2018.html), first Rust edition 2018 version) and `--maximum <version>` (default: latest version)
* add a `--search-strategy <name>` (or just `--strategy <name>`) command
* perform a binary search for the MSRV, instead of the default linear searc

**Comment by foresterre** [comment]
No possible with https://docs.rs/rust-releases/0.6.1/rust_releases/search/struct.Bisect.html

**Comment by foresterre** [comment]
implemented by #64

**Comment by danieleades** [comment]
is there a reason this isn't the default?

**Comment by foresterre** [comment]
Hi @danieleades, thanks for your question.

I think there are two reasons at the moment why it isn't the default:
1) The bisect implementation has not been battle tested and aside from my own use, I've received no feedback on how well the implementation performs. On the flip side, having it as the default may very well generate such feedback.
2) At the time of implementation there were some issues regarding different versions of `Cargo.lock` files. Older Cargo versions did not support newer lock files. When using bisection, this issue become much more prominent, as we would now install much older toolchains, while currently, most often the MSRV is a much more recent version of Rust which have support for the newer lock file. This issue can be alleviated by running `cargo msrv` with the `--ignore-lockfile` flag, but it also changes the behaviour since we now run a toolchain against unfrozen dependency versions. 

However, a binary search can significantly reduce the time necessary to determine the MSRV, especially when you also reduce the search space further by setting `--minimum <version>` (e.g. `1.31.0` for Rust edition 2018), so it's definitely a worth to think about, and to start a conversation about. 

What would be the primary reason(s) for you to have `--bisect` as the default?

**Comment by foresterre** [comment]
I've moved this conversion to https://github.com/foresterre/cargo-msrv/issues/97
