### ISSUE TITLE
Docker images

### ISSUE THREAD

**Issue by orhun** [foresterre/cargo-msrv#500]
Hello!

Is adding a `Dockerfile` for `cargo-msrv` and publishing Docker images on the roadmap?

This could be beneficial in a couple of ways:

1. Containerization.
2. A dedicated GitHub action could be created. ([*](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action))
3. Docker image could be utilized in GitLab CI.

I would like to work on a `Dockerfile` if this is applicable.

**Comment by foresterre** [comment]
It wasn't on the roadmap, but I would be happy to put it on the roadmap as I can see the added benefit 😄.
