### ISSUE TITLE
Tweak release profile settings

### ISSUE THREAD

**Issue by orhun** [foresterre/cargo-msrv#505]
It would be nice to tweak the [release](https://doc.rust-lang.org/cargo/reference/profiles.html#release) profile settings for binary/runtime optimizations. For example, enabling LTO and incrementing the optimization level would make the binary run faster (but makes the compilation slower).

I would like to submit a PR if applicable. Let me know what you think! 🐻 @foresterre

**Comment by foresterre** [comment]
Sure!
