### ISSUE TITLE
not working for projects targeting other target (missing target in toolchains)

### ISSUE THREAD

**Issue by rursprung** [foresterre/cargo-msrv#587]
if a project is targeting another target - generally the case for embedded projects - then the check will fail unless the target has been manually installed for all rust versions used by `cargo-msrv` in the check.

this will then fail with errors like these:
```
error[E0463]: can't find crate for `core`
  |
  = note: the `thumbv7em-none-eabihf` target may not be installed
  = help: consider downloading the target with `rustup target add thumbv7em-none-eabihf`
```

and thus `cargo-msrv` will eventually only report the current rust version as compatible as it's usually the only one installed with the appropriate targets.

this happens for crates which define `build.target` in their `.cargo/config`. you can e.g. test this with [this example](https://github.com/rtic-rs/rtic-examples/blob/master/rtic_v1/stm32f4_independent_watchdog/). (i had an even weirder experience when trying this: the first run of `cargo msrv` failed but after running `cargo check` a subsequent run of `cargo msrv` succeeded for stable rust).

`cargo-msrv` should recognise that a different target is needed and install this (if missing) for the toolchain which it's about to test.

i found #325 which _might_ be related to this?

tested using the following versions (latest available ones at this time) on Windows 11:
* cargo-msrv 0.15.1
* cargo & rust 1.66.1

**Comment by foresterre** [comment]
Yikes! I haven't found the time to test it out yet, but I'll note that we currently do not read any config defined in the `.cargo/config` files, which is not ideal. 

As a work around, it may work by running cargo msrv with the `--target` option, i.e. `cargo msrv --target thumbv7em-none-eabihf`, but I haven't tried whether it works in this instance yet.

**Comment by rursprung** [comment]
> As a work around, it may work by running cargo msrv with the `--target` option, i.e. `cargo msrv --target thumbv7em-none-eabihf`, but I haven't tried whether it works in this instance yet.

nope, that isn't working - i think `cargo-msrv` currently interprets `target` as `toolchain`:
```
$ cargo msrv --target thumbv7em-none-eabihf
Fetching index
Determining the Minimum Supported Rust Version (MSRV) for toolchain thumbv7em-none-eabihf
Using check command cargo check
Unable to install toolchain with `rustup install 1.61.0-thumbv7em-none-eabihf`.
```

while in reality the toolchain would still be for the local machine where it has to run but it'd have a target for cross-compilation.

this is done by using the typical `cargo toolchain install ${toolchain}` followed by `cargo target add --toolchain ${toolchain} ${target}` (w/o the `--toolchain` it'd just install it for the currently active toolchain, i.e. usually `stable` which is not what `cargo-msrv` would want to do).

**Comment by philpax** [comment]
Can confirm that this is also an issue when testing for WASM compilation. Not a huge issue for us at present, but would be nice to support installing the right Rust version and the WASM target for that version. (i.e. `cargo msrv --min 1.60.0 --target wasm32-wasi` fails with the same toolchain issue as above)

**Comment by Finomnis** [comment]
I looked through the code and came to the conclusion that this crate seems to have an incorrect understanding of the way toolchains work.

- `1.63.0-thumbv7em-none-eabihf` means that our **build machine** is a `thumbv7em-none-eabihf`. This is most likely always constant; a machine doesn't spontaneously change its type.
- The toolchain then has one or multiple installed **targets**. This is the **compilation target machine**, which is what the `--target` flag should actually control.

The current behavior, if being on an `x86_64-unknown-linux-gnu` machine and a `--target thumbv7em-none-eabihf` is specified and we want version `1.63.0`, is:
- `rustup install 1.63.0-thumbv7em-none-eabihf --profile minimal`

What **should** happen instead is:
- `rustup install 1.63.0 --profile minimal`
- `rustup target add --toolchain 1.63.0 thumbv7em-none-eabihf`

Sadly, this makes this crate completely unusable for cross compilation crates (as in many embedded crates) right now.

**Comment by foresterre** [comment]
> I looked through the code and came to the conclusion that this crate seems to have an incorrect understanding of the way toolchains work.
> 
>     * `1.63.0-thumbv7em-none-eabihf` means that our **build machine** is a `thumbv7em-none-eabihf`. This is most likely always constant; a machine doesn't spontaneously change its type.
> 
>     * The toolchain then has one or multiple installed **targets**. This is the **compilation target machine**, which is what the `--target` flag should actually control.
> 
> 
> The current behavior, if being on an `x86_64-unknown-linux-gnu` machine and a `--target thumbv7em-none-eabihf` is specified and we want version `1.63.0`, is:
> 
>     * `rustup install 1.63.0-thumbv7em-none-eabihf --profile minimal`
> 
> 
> What **should** happen instead is:
> 
>     * `rustup install 1.63.0 --profile minimal`
> 
>     * `rustup target add --toolchain 1.63.0 thumbv7em-none-eabihf`
> 
> 
> Sadly, this makes this crate completely unusable for cross compilation crates (like many embedded crates).

Thank you for the reply. I split your reply into #824.
Based on your reply, I presume that checks should also run from the build machine against the test target, like so (with your example):

```
rustup run 1.63.0 cargo check --target thumbv7em-none-eabihf
```

**Comment by foresterre** [comment]
Feel free to re-open if it still doesn't work with cargo-msrv >= https://github.com/foresterre/cargo-msrv/releases/tag/v0.16.0-beta.17

**Comment by rursprung** [comment]
> Feel free to re-open if it still doesn't work with cargo-msrv >= https://github.com/foresterre/cargo-msrv/releases/tag/v0.16.0-beta.17

just tested it, seems to work fine now - thanks for fixing this! looking forward to seeing this in a stable release soon!
