### ISSUE TITLE
Compatibility with workspace inheritance

### ISSUE THREAD

**Issue by max-sixty** [foresterre/cargo-msrv#590]
Related to https://github.com/foresterre/cargo-msrv/issues/295, but I think not the same.

Currently running `cargo msrv verify` on https://github.com/prql/prql within `prql-compiler` raises an error:

```
❯ cargo msrv verify
Fetching index
Unable to find key 'package.rust-version' (or 'package.metadata.msrv') in '/Users/maximilian/workspace/prql/prql-compiler/Cargo.toml'
```

I think that's because we use workspace inheritance, taking the rust version from the workspace.

Is that something that could be supported?

Thanks!

**Comment by gautamprikshit1** [comment]
Any guidance/help on this one??

**Comment by foresterre** [comment]
> Any guidance/help on this one??

As in: you want to help with implementing this, or how you can workaround it right now? :)

**Comment by foresterre** [comment]
Awesome!

Before implementing anything though, we'll need to think about what the _proper workspace support_ will entail. For this, I wanted to first look in detail at how Cargo handles workspaces (on a user and implementation level), and then what other cargo plugins currently do. Probably we'll want to mimic Cargo where we can.

I'll try to find some time this week to think this through and write it down.
If you have opinions or would like to help with the prior research, feel welcome to write about it :). If you rather only implement ideas, that's also fine!

**Comment by foresterre** [comment]
@gautamprikshit1 Do you still want to give it a shot?

**Comment by not-my-profile** [comment]
I really don't see any reason why cargo-msrv should reimplement the Cargo config resolution, when it can just obtain the resolved configuration via `cargo metadata`. In fact this crate does already depend on [cargo_metadata](https://docs.rs/cargo_metadata/) for the dependency graph resolver.

The only obstacle is that the `cargo_metadata` crate apparently uses a wrong type for the `rust_version` field, but I have just submitted a PR there to remedy that: oli-obk/cargo_metadata#243.

Once that type is fixed in `cargo_metadata`, I am happy to submit a PR here to use `cargo_metadata` for the config resolution of `cargo msrv verify`, to resolve this issue :)

**Comment by foresterre** [comment]
> Once that type is fixed in cargo_metadata, I am happy to submit a PR here to use cargo_metadata for the config resolution of cargo msrv verify, to resolve this issue :)

That would be wonderful 😄. Thanks!

**Comment by spenserblack** [comment]
I'm just getting back into Rust after a long hiatus, so please forgive me if this is silly. But doesn't `cargo package` convert the manifest into a more backwards-compatible format, including inheritance? With issues like this `cargo msrv` is actually returning the MSRV for *development,* but couldn't the MSRV for the end user be obtained by checking against `target/package/FOO-X.Y.Z`?

**Comment by CGMossa** [comment]
@not-my-profile hej! I see that https://github.com/foresterre/cargo-msrv/issues/590 has been merged. Do you still remember how you would fix the workspace issue with that now done?

**Comment by foresterre** [comment]
I think to solve this issue, we need:

1. Fix https://github.com/foresterre/cargo-msrv/pull/802 (it fails on the exact fix referenced here before, where the `cargo msrv list` prints the MSRV of dependencies, and used to use the VersionReq, but now it is a Version instead. https://github.com/oli-obk/cargo_metadata/pull/244) 
2. Use `cargo metadata` to infer the workspace variables, and set them as appropriate (this can possibly be done incrementally) 

Feel free to submit a PR

**Comment by Jefffrey** [comment]
Hey, was just wondering on the status of this issue now? If it's not on anyone's radar at the moment, I can take a shot at implementing a PR to push this over the finish line :slightly_smiling_face:

**Comment by foresterre** [comment]
I don't think anyone is working on thus right now :)

**Comment by max-sixty** [comment]
I think we can close, thanks to https://github.com/foresterre/cargo-msrv/pull/882

**Comment by eitsupi** [comment]
Hello.
I have tried the new cargo-msrv and it seems that `cargo-msrv msrv find` supports workspaces root (great!) but not `verify`.
Should I open another issue?

**Comment by foresterre** [comment]
> Hello. I have tried the new cargo-msrv and it seems that `cargo-msrv msrv find` supports workspaces root (great!) but not `verify`. Should I open another issue?

Please do!
