### ISSUE TITLE
Unable to install toolchain with `rustup install 1.63.0-thumbv7em-none-eabihf`

### ISSUE THREAD

**Issue by LuckyTurtleDev** [foresterre/cargo-msrv#702]
Cargo-msrv fails to check on `thumbv7em-none-eabihf` target.
I have tested this with this crate: https://github.com/LuckyTurtleDev/m3/tree/fb1a99c1f5437179eb372797ebc4ee10ab1207ea/pybadge
```
❯ cargo msrv --target thumbv7em-none-eabihf
Fetching index
Determining the Minimum Supported Rust Version (MSRV) for toolchain thumbv7em-none-eabihf
Using check command cargo check
Unable to install toolchain with `rustup install 1.63.0-thumbv7em-none-eabihf`.
```

Not sure if this is related to #587, since I get an different error message.

**Comment by foresterre** [comment]
This is indeed the same issue as #587.

The release [index](https://dev-static.rust-lang.org/dist/2022-08-09/index.html) for Rust 1.63 does not contain the `thumbv7em-none-eabihf` target.
