### ISSUE TITLE
Custom check?

### ISSUE THREAD

**Issue by polarathene** [foresterre/cargo-msrv#812]
I recently tried `cargo-msrv` on a project and it correctly detected the MSRV which is a great.

Another user noticed the CI did not like the MSRV though, and that was due to the MSRV for dev-dependencies was different. `cargo check --tests` for example would fail.

Is this something `cargo-msrv` could also support? It seems it'd just need to support adjusting the check command to allow setting options?

**Comment by polarathene** [comment]
Looks like this was being tackled in May?:
- https://github.com/foresterre/cargo-msrv/pull/421
- https://github.com/foresterre/cargo-msrv/pull/674

Related issues:
- https://github.com/foresterre/cargo-msrv/issues/408

**Comment by foresterre** [comment]
In today's cargo msrv, you can run `cargo msrv -- cargo check --tests` to run cargo msrv with your command.

Would this resolve your question?

**Comment by polarathene** [comment]
Yes! Sorry, I see that this was actually covered on the README and CLI help output. For some reason I completely missed it from both 😬 

I had tried searching through the issues (_and open PRs as linked above_), thinking this hadn't been covered. The README has had it since Jan 2022, and in Dec 2022 [an example specifically for this `cargo check --tests` command was contributed](https://github.com/foresterre/cargo-msrv/pull/577) 😓 

---

For quick reference if anyone lands on this issue:

![image](https://github.com/foresterre/cargo-msrv/assets/5098581/5a271a39-b7fc-4a68-be4a-ef75b8d43c74)

![image](https://github.com/foresterre/cargo-msrv/assets/5098581/3bd0883c-8b7c-4c0f-88a8-624354cd1ad3)

![image](https://github.com/foresterre/cargo-msrv/assets/5098581/0dc748a2-b0dc-4707-8b35-7d7c51a16b9b)

**Comment by foresterre** [comment]
No worries! Glad it works!
