### ISSUE TITLE
Posible to install clippy for using it as a check?

### ISSUE THREAD

**Issue by hoijui** [foresterre/cargo-msrv#840]
I want to use `cargo clippy` as the check, so I would need to be able to specify that rustup should also install clippy for each rust version to be checked. Is this possible? does this make sense?

**Comment by hoijui** [comment]
Is this possibly related to #701?

**Comment by foresterre** [comment]
Not possible out of the box right now, but should certainly be possible. Started working on this now.

**Comment by foresterre** [comment]
Should now be possible, with `cargo install cargo-msrv --version 0.16.0-beta.18`, and `cargo msrv (...) --add-component clippy -- cargo clippy`

**Comment by hoijui** [comment]
woow.. thank you @foresterre ! :-)
that was quick. have a good evening and week!
