### ISSUE TITLE
Attach binaries as part of releases

### ISSUE THREAD

**Issue by thomaseizinger** [foresterre/cargo-msrv#88]
I am interested in publishing a (binary) package to AUR for this tool. To make this easier, it would be nice if (at least) a Linux build would be attached to each release.

Would you be open to adding a GitHub workflow that attaches a binary to each release? I am happy to submit a PR for that.

**Comment by foresterre** [comment]
Certainly!

**Comment by foresterre** [comment]
Thanks!
