### ISSUE TITLE
 Make `bisect` the default search strategy

### ISSUE THREAD

**Issue by foresterre** [foresterre/cargo-msrv#97]
is there a reason this isn't the default?

_Originally posted by @danieleades in https://github.com/foresterre/cargo-msrv/issues/45#issuecomment-922481683_

**Comment by foresterre** [comment]
> 
> 
> Hi @danieleades, thanks for your question.
> 
> I think there are two reasons at the moment why it isn't the default:
> 
>     1. The bisect implementation has not been battle tested and aside from my own use, I've received no feedback on how well the implementation performs. On the flip side, having it as the default may very well generate such feedback.
> 
>     2. At the time of implementation there were some issues regarding different versions of `Cargo.lock` files. Older Cargo versions did not support newer lock files. When using bisection, this issue become much more prominent, as we would now install much older toolchains, while currently, most often the MSRV is a much more recent version of Rust which have support for the newer lock file. This issue can be alleviated by running `cargo msrv` with the `--ignore-lockfile` flag, but it also changes the behaviour since we now run a toolchain against unfrozen dependency versions.
> 
> 
> However, a binary search can significantly reduce the time necessary to determine the MSRV, especially when you also reduce the search space further by setting `--minimum <version>` (e.g. `1.31.0` for Rust edition 2018), so it's definitely a worth to think about, and to start a conversation about.
> 
> What would be the primary reason(s) for you to have `--bisect` as the default?

**Comment by danieleades** [comment]
i'm using 'bisect' to find the msrv on new projects. it's significantly faster than the linear search.

I'm also using the 2018 edition as a minimum. perhaps the edition set in `cargo.toml` should be respected as a minimum? or at least, the editions could be used as aliases with the `--min` argument. That's a different issue of course.
